name: password_vault
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.3
  crypt: ^4.3.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_remote_config: ^4.3.6
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  stacked_services: ^1.3.0
  stacked_themes: ^0.3.12
  stacked: ^3.4.1+1
  string_validator: ^1.0.2
  animations: ^2.0.10
  flutter_animate: ^4.3.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.3
  stacked_generator: ^1.5.1

flutter:
  uses-material-design: true
