// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArFV58AvfYK3qp_g6YlgLvjvzn2-xa6QI',
    appId: '1:1045903185033:web:0c76630337cc13c356e258',
    messagingSenderId: '1045903185033',
    projectId: 'password-vault-db554',
    authDomain: 'password-vault-db554.firebaseapp.com',
    storageBucket: 'password-vault-db554.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9KOYdakiVcdlr1kmyjW51_D2muV25po8',
    appId: '1:1045903185033:android:1c23758049c2537556e258',
    messagingSenderId: '1045903185033',
    projectId: 'password-vault-db554',
    storageBucket: 'password-vault-db554.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmH8nbbnubuxAbUakkzMw50qt_t1xnoRs',
    appId: '1:1045903185033:ios:d0de4e95e954264456e258',
    messagingSenderId: '1045903185033',
    projectId: 'password-vault-db554',
    storageBucket: 'password-vault-db554.appspot.com',
    iosBundleId: 'com.example.passwordVault',
  );
}
